FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-bookworm-slim AS builder
WORKDIR /app
ARG NEXT_PUBLIC_HELA_RPC
ARG NEXT_PUBLIC_CHAIN_ID
ARG NEXT_PUBLIC_HLUSD_ADDRESS
ARG NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS
ARG NEXT_PUBLIC_AGENT_ESCROW_ADDRESS
ARG NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS
ARG NEXT_PUBLIC_PLATFORM_FEE_BPS
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_GEMINI_API_KEY
ENV NEXT_PUBLIC_HELA_RPC=${NEXT_PUBLIC_HELA_RPC}
ENV NEXT_PUBLIC_CHAIN_ID=${NEXT_PUBLIC_CHAIN_ID}
ENV NEXT_PUBLIC_HLUSD_ADDRESS=${NEXT_PUBLIC_HLUSD_ADDRESS}
ENV NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS=${NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS}
ENV NEXT_PUBLIC_AGENT_ESCROW_ADDRESS=${NEXT_PUBLIC_AGENT_ESCROW_ADDRESS}
ENV NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS=${NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS}
ENV NEXT_PUBLIC_PLATFORM_FEE_BPS=${NEXT_PUBLIC_PLATFORM_FEE_BPS}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_PUBLIC_GEMINI_API_KEY=${NEXT_PUBLIC_GEMINI_API_KEY}
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 8080
CMD ["node", "server.js"]
