import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353535",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary": "#1a1c1c",
        "secondary": "#c6c6c7",
        "on-background": "#e2e2e2",
        "primary-fixed-dim": "#454747",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#e2e2e2",
        "surface": "#131313",
        "secondary-fixed": "#c6c6c7",
        "on-secondary-fixed-variant": "#3a3c3c",
        "surface-tint": "#c6c6c7",
        "tertiary-fixed-dim": "#930010",
        "outline-variant": "#474747",
        "surface-container-high": "#2a2a2a",
        "on-primary": "#1a1c1c",
        "on-primary-fixed": "#ffffff",
        "error-container": "#93000a",
        "on-secondary-container": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "inverse-surface": "#e2e2e2",
        "inverse-primary": "#5d5f5f",
        "primary": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "inverse-on-surface": "#303030",
        "on-tertiary": "#410003",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#ffdad6",
        "on-tertiary-container": "#000000",
        "secondary-container": "#454747",
        "on-surface-variant": "#c6c6c6",
        "outline": "#919191",
        "background": "#000000",
        "surface-container-low": "#1b1b1b",
        "secondary-fixed-dim": "#aaabab",
        "surface-container": "#1f1f1f",
        "tertiary-fixed": "#c00018",
        "on-error": "#690005",
        "tertiary-container": "#ff544e",
        "on-surface": "#e2e2e2",
        "primary-fixed": "#5d5f5f",
        "surface-container-highest": "#353535",
        "tertiary": "#ffdad6",
        "on-primary-container": "#000000",
        "primary-container": "#d4d4d4",
        "live-signal": "#FF3B3B",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Bebas Neue", "sans-serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  darkMode: "class",
  plugins: [],
};

export default config;
