/**
 * In-memory storage and execution runtime for generated agents.
 * Exports:
 * - storeAgent: register a deployed/generated agent in memory
 * - getAgent: fetch stored agent metadata
 * - runAgent: execute stored runtime code safely and normalize output
 */

import { callGemini } from "./gemini";
import type { AgentObject, ExecutionResult, StoredAgent } from "../types/agent";
import { getStoredAgent, upsertStoredAgent } from "./automationStore";

const agentStore = new Map<string, StoredAgent>();

function errorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  return "Unknown execution error";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * Stores a generated/deployed agent in memory for runtime execution.
 * @param agentId Unique on-chain/off-chain identifier of the agent.
 * @param agent Agent metadata and schema.
 * @param executionCode Executable function source returned by generation pipeline.
 * @param developerAddress Wallet address of the developer who deployed the agent.
 */
export async function storeAgent(
  agentId: string,
  agent: AgentObject,
  executionCode: string,
  developerAddress: string,
  agentWalletAddress: string,
  agentWalletPrivateKey: string
): Promise<void> {
  const record: StoredAgent = {
    agent,
    executionCode,
    deployedAt: new Date().toISOString(),
    developerAddress,
    agentId,
    agentWalletAddress,
    agentWalletPrivateKey,
    status: "active"
  };

  agentStore.set(agentId, record);
  await upsertStoredAgent(record);
}

/**
 * Retrieves a stored agent from in-memory runtime storage.
 * @param agentId Unique agent identifier.
 * @returns Stored agent payload if found, otherwise undefined.
 */
export async function getAgent(agentId: string): Promise<StoredAgent | undefined> {
  const inMemory = agentStore.get(agentId);
  if (inMemory) {
    return inMemory;
  }

  const stored = await getStoredAgent(agentId);
  if (stored) {
    agentStore.set(agentId, stored);
  }
  return stored ?? undefined;
}

/**
 * Runs a stored agent using dynamic runtime code generated by Gemini.
 *
 * new Function() is intentionally used here because execution logic is generated at runtime,
 * persisted as source text, and must be evaluated server-side without bundling static agent code.
 * @param agentId Unique agent identifier.
 * @param config User-provided execution configuration.
 * @returns Normalized execution result object. This function never throws.
 */
export async function runAgent(
  agentId: string,
  config: Record<string, any>
): Promise<ExecutionResult> {
  try {
    const stored = await getAgent(agentId);
    if (!stored) {
      throw new Error("Agent not found");
    }

    const compiled = new Function("callGemini", `return (${stored.executionCode})`)(callGemini);
    if (typeof compiled !== "function") {
      throw new Error("Generated execution code did not produce an executable function");
    }

    const rawResult = await compiled(config);
    const executedAt = new Date().toISOString();

    if (isRecord(rawResult)) {
      const success = typeof rawResult.success === "boolean" ? rawResult.success : true;
      const resultText =
        typeof rawResult.result === "string" ? rawResult.result : JSON.stringify(rawResult.result ?? rawResult);
      const data = isRecord(rawResult.data) ? (rawResult.data as Record<string, any>) : undefined;

      return {
        success,
        result: resultText,
        data,
        executedAt
      };
    }

    return {
      success: true,
      result: typeof rawResult === "string" ? rawResult : JSON.stringify(rawResult),
      executedAt
    };
  } catch (error: unknown) {
    return {
      success: false,
      result: errorMessage(error),
      executedAt: new Date().toISOString()
    };
  }
}
