/**
 * In-memory storage and execution runtime for generated agents.
 * Exports:
 * - storeAgent: register a deployed/generated agent in memory
 * - getAgent: fetch stored agent metadata
 * - runAgent: execute stored runtime code safely and normalize output
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { callGemini } from "./gemini";
import type { AgentObject, ExecutionResult, StoredAgent } from "../types/agent";

const STORE_FILE_PATH = join(process.cwd(), ".runtime", "agent-store.json");

const globalStore = globalThis as typeof globalThis & {
  __troviaAgentStore?: Map<string, StoredAgent>;
};

const agentStore = globalStore.__troviaAgentStore ?? new Map<string, StoredAgent>();
if (!globalStore.__troviaAgentStore) {
  globalStore.__troviaAgentStore = agentStore;
}

function errorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  return "Unknown execution error";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isStoredAgent(value: unknown): value is StoredAgent {
  if (!isRecord(value)) {
    return false;
  }

  return (
    isRecord(value.agent) &&
    typeof value.executionCode === "string" &&
    typeof value.deployedAt === "string" &&
    typeof value.developerAddress === "string" &&
    typeof value.agentId === "string"
  );
}

function readPersistedStore(): Record<string, StoredAgent> {
  try {
    if (!existsSync(STORE_FILE_PATH)) {
      return {};
    }

    const raw = readFileSync(STORE_FILE_PATH, "utf8");
    if (!raw.trim()) {
      return {};
    }

    const parsed = JSON.parse(raw) as unknown;
    if (!isRecord(parsed)) {
      return {};
    }

    const normalized: Record<string, StoredAgent> = {};
    for (const [key, value] of Object.entries(parsed)) {
      if (isStoredAgent(value)) {
        normalized[key] = value;
      }
    }

    return normalized;
  } catch {
    return {};
  }
}

function writePersistedStore(store: Record<string, StoredAgent>): void {
  const dir = dirname(STORE_FILE_PATH);
  mkdirSync(dir, { recursive: true });
  writeFileSync(STORE_FILE_PATH, JSON.stringify(store, null, 2), "utf8");
}

/**
 * Stores a generated/deployed agent in memory for runtime execution.
 * @param agentId Unique on-chain/off-chain identifier of the agent.
 * @param agent Agent metadata and schema.
 * @param executionCode Executable function source returned by generation pipeline.
 * @param developerAddress Wallet address of the developer who deployed the agent.
 */
export function storeAgent(
  agentId: string,
  agent: AgentObject,
  executionCode: string,
  developerAddress: string
): void {
  const stored: StoredAgent = {
    agent,
    executionCode,
    deployedAt: new Date().toISOString(),
    developerAddress,
    agentId
  };

  agentStore.set(agentId, stored);

  const persisted = readPersistedStore();
  persisted[agentId] = stored;
  writePersistedStore(persisted);
}

/**
 * Retrieves a stored agent from in-memory runtime storage.
 * @param agentId Unique agent identifier.
 * @returns Stored agent payload if found, otherwise undefined.
 */
export function getAgent(agentId: string): StoredAgent | undefined {
  const inMemory = agentStore.get(agentId);
  if (inMemory) {
    return inMemory;
  }

  const persisted = readPersistedStore();
  const fromDisk = persisted[agentId];
  if (fromDisk) {
    agentStore.set(agentId, fromDisk);
    return fromDisk;
  }

  return undefined;
}

/**
 * Runs a stored agent using dynamic runtime code generated by Gemini.
 *
 * new Function() is intentionally used here because execution logic is generated at runtime,
 * persisted as source text, and must be evaluated server-side without bundling static agent code.
 * @param agentId Unique agent identifier.
 * @param config User-provided execution configuration.
 * @returns Normalized execution result object. This function never throws.
 */
export async function runAgent(
  agentId: string,
  config: Record<string, any>
): Promise<ExecutionResult> {
  try {
    const stored = getAgent(agentId);
    if (!stored) {
      throw new Error("Agent not found");
    }

    const compiled = new Function("callGemini", `return (${stored.executionCode})`)(callGemini);
    if (typeof compiled !== "function") {
      throw new Error("Generated execution code did not produce an executable function");
    }

    const rawResult = await compiled(config);
    const executedAt = new Date().toISOString();

    if (isRecord(rawResult)) {
      const success = typeof rawResult.success === "boolean" ? rawResult.success : true;
      const resultText =
        typeof rawResult.result === "string" ? rawResult.result : JSON.stringify(rawResult.result ?? rawResult);
      const data = isRecord(rawResult.data) ? (rawResult.data as Record<string, any>) : undefined;

      return {
        success,
        result: resultText,
        data,
        executedAt
      };
    }

    return {
      success: true,
      result: typeof rawResult === "string" ? rawResult : JSON.stringify(rawResult),
      executedAt
    };
  } catch (error: unknown) {
    return {
      success: false,
      result: errorMessage(error),
      executedAt: new Date().toISOString()
    };
  }
}
