#!/usr/bin/env bash

set -euo pipefail

if ! command -v gcloud >/dev/null 2>&1; then
  echo "gcloud CLI is required."
  exit 1
fi

PROJECT_ID="${GCP_PROJECT_ID:-}"
REGION="${GCP_REGION:-asia-south1}"
SERVICE="${GCP_CLOUD_RUN_SERVICE:-trovia-app}"
REPOSITORY="${GCP_ARTIFACT_REPOSITORY:-trovia}"
IMAGE_NAME="${GCP_IMAGE_NAME:-trovia-app}"
TAG="${GCP_IMAGE_TAG:-latest}"
ENV_FILE="${GCP_ENV_FILE:-.env}"

if [[ -z "$PROJECT_ID" ]]; then
  echo "Set GCP_PROJECT_ID before running this script."
  exit 1
fi

read_env_value() {
  local key="$1"
  local file="$2"

  if [[ ! -f "$file" ]]; then
    return 0
  fi

  grep -E "^${key}=" "$file" | tail -n 1 | sed -E "s/^${key}=//"
}

IMAGE_URI="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG}"

NEXT_PUBLIC_HELA_RPC="$(read_env_value "NEXT_PUBLIC_HELA_RPC" "$ENV_FILE")"
NEXT_PUBLIC_CHAIN_ID="$(read_env_value "NEXT_PUBLIC_CHAIN_ID" "$ENV_FILE")"
NEXT_PUBLIC_HLUSD_ADDRESS="$(read_env_value "NEXT_PUBLIC_HLUSD_ADDRESS" "$ENV_FILE")"
NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS="$(read_env_value "NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS" "$ENV_FILE")"
NEXT_PUBLIC_AGENT_ESCROW_ADDRESS="$(read_env_value "NEXT_PUBLIC_AGENT_ESCROW_ADDRESS" "$ENV_FILE")"
NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS="$(read_env_value "NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS" "$ENV_FILE")"
NEXT_PUBLIC_PLATFORM_FEE_BPS="$(read_env_value "NEXT_PUBLIC_PLATFORM_FEE_BPS" "$ENV_FILE")"
NEXT_PUBLIC_SUPABASE_URL="$(read_env_value "NEXT_PUBLIC_SUPABASE_URL" "$ENV_FILE")"
NEXT_PUBLIC_SUPABASE_ANON_KEY="$(read_env_value "NEXT_PUBLIC_SUPABASE_ANON_KEY" "$ENV_FILE")"
NEXT_PUBLIC_GEMINI_API_KEY="$(read_env_value "NEXT_PUBLIC_GEMINI_API_KEY" "$ENV_FILE")"

echo "Deploying Trovia to Cloud Run..."
echo "Project: ${PROJECT_ID}"
echo "Region: ${REGION}"
echo "Service: ${SERVICE}"
echo "Image: ${IMAGE_URI}"

gcloud builds submit \
  --project "${PROJECT_ID}" \
  --config cloudbuild.yaml \
  --substitutions "_SERVICE=${SERVICE},_REGION=${REGION},_IMAGE_URI=${IMAGE_URI},_NEXT_PUBLIC_HELA_RPC=${NEXT_PUBLIC_HELA_RPC},_NEXT_PUBLIC_CHAIN_ID=${NEXT_PUBLIC_CHAIN_ID},_NEXT_PUBLIC_HLUSD_ADDRESS=${NEXT_PUBLIC_HLUSD_ADDRESS},_NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS=${NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS},_NEXT_PUBLIC_AGENT_ESCROW_ADDRESS=${NEXT_PUBLIC_AGENT_ESCROW_ADDRESS},_NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS=${NEXT_PUBLIC_AGENT_EXECUTOR_ADDRESS},_NEXT_PUBLIC_PLATFORM_FEE_BPS=${NEXT_PUBLIC_PLATFORM_FEE_BPS},_NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL},_NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY},_NEXT_PUBLIC_GEMINI_API_KEY=${NEXT_PUBLIC_GEMINI_API_KEY}"
